---
name: "Simulated device build"
on:
  push:
    branches:
      - master
jobs:
  build-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./proof-of-concept/simulation/sample-device/build-docker-image.sh
