---
name: "SLS SDK test"
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: simulation/sls-sdk/package-lock.json
      - working-directory: simulation/sls-sdk/
        run: npm install
      - working-directory: simulation/sls-sdk/
        run: npm run test
  acceptance-test:
    name: Acceptance Test
    runs-on: ubuntu-20.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9.1'
          cache: 'npm'
          cache-dependency-path: |
            simulation/sls-sdk/package-lock.json
            simulation/acceptance-test/package-lock.json
      - working-directory: simulation/sls-sdk/
        run: npm install
      - working-directory: simulation/acceptance-test/
        run: npm install
      - working-directory: simulation/acceptance-test/
        run: npm run test
