---
name: "UML diagrams build"
on:
  push:
    branches:
      - master
jobs:
  build-diagrams:
    runs-on: ubuntu-20.04
    container:
      image: think/plantuml:1.2020.5
      options: '--entrypoint ""'
    steps:
      - uses: actions/checkout@v2
      - run: java -jar /plantuml.jar docs/final-report/diagrams/*.plnt
      - uses: actions/upload-artifact@v2
        with:
          name: Diagrams
          path: docs/final-report/diagrams/*.png
